### ISSUE TITLE
No documentation in EmuSubroutines for WiimoteEmu::Spy()'s #if 0 block

### ISSUE THREAD

**Issue by lioncash** [mirror/dolphin-emu#45]
Hey there John P. You had this code committed to Dolphin a while ago (in 2013 actually): https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/HW/WiimoteEmu/EmuSubroutines.cpp#L36

This is evidenced the following commit [here](https://github.com/dolphin-emu/dolphin/commit/0fd3acd1#diff-65342fd62daa696cc936c5a87cd66f4aR37). There's no documentation on whether or not this is purely a function for logging, or if it's genuinely broken code that never had gotten fixed. I was just wondering if you could tell me, so it can be noted and make maintainability of that code much easier in the future.

**Comment by john-peterson** [comment]
> There's no documentation on whether or not this is purely a function for logging, or if it's genuinely broken code that never had gotten fixed.

it's for logging the real and emu wiimote

i've used it to fix the emu wiimote and real wiimote audio

it's #if 0 to save processing because it's only used when debugging

there's an improved version here https://github.com/john-peterson/dolphin-emu/blob/input/Source/Core/Core/Src/HW/WiimoteEmu/EmuSubroutines.cpp#L49

**Comment by lioncash** [comment]
Thanks a bunch, I'll make a commit detailing it's to be enabled for logging purposes.
